apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: conduit-prod
  labels:
    app: backend
data:
  db_name: "conduit"
  # This will be overridden by Ansible during deployment with actual Cloud SQL IP
  db_hostname: "postgres-primary-0.postgres-service.conduit-prod.svc.cluster.local"
  db_dialect: "postgres"
