apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: conduit-prod
  labels:
    app: backend
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
  - name: http
    protocol: TCP
    port: 3001
    targetPort: 3001
  sessionAffinity: ClientIP
