[docker_hosts]
# Adicionar IP da VM Docker aqui
# Exemplo: 20.1.2.3

[ci_hosts]
# Adicionar IP da VM CI aqui
# Exemplo: 20.1.2.4

[all:vars]
ansible_user=azureuser
ansible_python_interpreter=/usr/bin/python3
