[docker_hosts]
# IP será preenchido dinamicamente pelo GitHub Actions

[all:vars]
ansible_user=gcpuser
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'

